# Generated by Django 2.0.13 on 2019-09-25 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('author', models.CharField(max_length=45)),
                ('publish', models.CharField(max_length=45)),
                ('isbn', models.CharField(max_length=15)),
                ('women10', models.FloatField()),
                ('women60', models.FloatField()),
                ('women50', models.FloatField()),
                ('women40', models.FloatField()),
                ('women30', models.FloatField()),
                ('women20', models.FloatField()),
                ('men30', models.FloatField()),
                ('men40', models.FloatField()),
                ('men50', models.FloatField()),
                ('men20', models.FloatField()),
                ('men60', models.FloatField()),
                ('men10', models.FloatField()),
                ('url', models.CharField(max_length=255)),
                ('story', models.TextField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cossim',
            fields=[
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='cossim_a', serialize=False, to='book_reco.Books')),
                ('sim', models.FloatField()),
            ],
            options={
                'db_table': 'cossim',
                'managed': False,
            },
        ),
    ]
